# GENERAL
server:
  port: 8080

# DATABASE
spring:
  datasource:
    url: jdbc:mysql://tiendaonline.c70wmaqweakr.us-east-2.rds.amazonaws.com:3306/tiendaonline?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: 2215256994
    driver-class-name: com.mysql.cj.jdbc.Driver

# SISTEMA EXTERNO RENAPER
sistema:
  externo:
    identificador: 3d1f8d6b-cd96-4651-b760-a30a571beb52
    clave: casa1250

  # CLAVE PUBLICA DEL RENAPER
  renaper:
    modulo: 9BJ0WxXATSJ6KtiSHhglSd3kgc6j5kXLp8sx5hm5KN2Y8H1uygVrPAJGBqPEIgRpMHG8yMFyKh2hXLSnZNLtZ+7c+fMIUYJYARS8f4yxF3CpkMtVW4wJ5Sbg99vIyi8Hi/134QuwU9ghYKiGgaYEvsQo5P9R+y/MiJrclETu5mkUdazs0Sua5+WdnsmJqykVxrfHtgvlavtmhF2B8zUWWOb8zdPgWqzxULt4RHWIasdf6GxzG+XGK+6jyNfb4DpUJQBlHssVGgflNEukoYefTcqx865JeGMeIBJzmxceiD2PrEnDsHHYk8w5/2dAWbnf8Pk19T3CXDDd73MLiPR5xQ==
    exponencial: AQAB

# CONFIGURACIONES DE CLOUD


# Arreglar error de AWS
